# Generated by Django 3.1.7 on 2021-11-22 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aprobacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprobado', models.CharField(max_length=50, verbose_name='Aprobado si/no')),
                ('fechaparobado', models.DateField(verbose_name='Fecha de aprobación')),
                ('aceptado', models.CharField(max_length=50, verbose_name='Aceptado si/no')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=50, verbose_name='Id')),
                ('name', models.TextField(verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Radicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaRadicacion', models.DateField(verbose_name='Fecha de radicación')),
                ('NumeroFactura', models.CharField(max_length=50, verbose_name='Número de factura')),
                ('ValorFactura', models.IntegerField(verbose_name='Valor de la factura')),
                ('FechaFactura', models.DateField(verbose_name='Fecha de la factura')),
                ('Estamento', models.CharField(max_length=50, verbose_name='Afiliado')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.proveedor', verbose_name='Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Revisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=50, verbose_name='Id')),
                ('name', models.TextField(verbose_name='Nombre')),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='course',
        ),
        migrations.DeleteModel(
            name='Signature',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.AddField(
            model_name='radicacion',
            name='revisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.revisor', verbose_name='Revisor'),
        ),
        migrations.AddField(
            model_name='aprobacion',
            name='radicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.radicacion', verbose_name='Radicacion'),
        ),
    ]
