# Generated by Django 3.1.7 on 2021-11-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprobacion',
            name='aprobacion_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Código de la aprobación'),
        ),
        migrations.AlterField(
            model_name='radicacion',
            name='radicacion_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Código de la radicación'),
        ),
    ]
