# Generated by Django 3.1.7 on 2021-11-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20211122_0309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aprobacion',
            old_name='aprobacion_id',
            new_name='Aprobacion_Id',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='cod',
            new_name='Cod_Proveedor',
        ),
        migrations.RenameField(
            model_name='radicacion',
            old_name='radicacion_id',
            new_name='Radicacion_Id',
        ),
        migrations.RenameField(
            model_name='revisor',
            old_name='cod',
            new_name='Cod_Revisor',
        ),
        migrations.AlterField(
            model_name='radicacion',
            name='Estamento',
            field=models.CharField(max_length=50, verbose_name='Estamento'),
        ),
    ]
