# Generated by Django 3.1.7 on 2021-11-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20211122_0202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aprobacion',
            old_name='fechaparobado',
            new_name='FechaAprobado',
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='cod',
            field=models.CharField(max_length=50, verbose_name='Nit'),
        ),
    ]
